#!/usr/bin/env python

import os
import sys


if len(sys.argv) < 3:
    sys.stderr.write('Usage: ' + os.path.basename(sys.argv[0]) + ' DWB_BOOKMARKS_FILE OUTPUT_FILE')
    sys.exit(1)

with open(sys.argv[1]) as i:
    with open(sys.argv[2], 'w') as o:
        o.write('\n'.join(':bmark -title "%s" %s' % tuple(reversed(l.split(' ', 1))) for l in i.read().splitlines()))

sys.stdout.write('To import bookmarks into pentadactyl:\n    :source ' + os.path.abspath(sys.argv[2]))
